# Generated by Django 5.1.3 on 2024-12-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_interview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='score',
        ),
    ]
